framework:
    secret: '%env(APP_SECRET)%'
    session: true

    default_locale: ru
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - ru

    exceptions:
        Assert\AssertionFailedException:
            log_level: notice
            status_code: 422

        Symfony\Component\Messenger\Exception\HandlerFailedException:
            log_level: notice
            status_code: 422

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
