<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260407184643 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // catalog_products
        $this->addSql('CREATE TABLE catalog_products (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            sku_code VARCHAR(255) NOT NULL,
            sku_name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');

        // catalog_product_attributes
        $this->addSql('CREATE TABLE catalog_product_attributes (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            product_id INT NOT NULL,
            attr_key VARCHAR(255) NOT NULL,
            attr_value TEXT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_747A21D54584665A ON catalog_product_attributes (product_id)');

        // catalog_product_images
        $this->addSql('CREATE TABLE catalog_product_images (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            product_id INT NOT NULL,
            path VARCHAR(255) NOT NULL,
            is_cover BOOLEAN DEFAULT FALSE NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_1116EDC34584665A ON catalog_product_images (product_id)');

        // users
        $this->addSql('CREATE TABLE users (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(180) NOT NULL,
            name VARCHAR(180) NOT NULL,
            password VARCHAR(255) NOT NULL,
            type VARCHAR(50) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');

        // rbac_roles
        $this->addSql('CREATE TABLE rbac_roles (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            permissions JSON NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_487801545E237E06 ON rbac_roles (name)');

        // rbac_user_roles
        $this->addSql('CREATE TABLE rbac_user_roles (
            user_id INT NOT NULL,
            role_id INT NOT NULL,
            PRIMARY KEY (user_id, role_id)
        )');
        $this->addSql('CREATE INDEX IDX_C4230A76A76ED395 ON rbac_user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_C4230A76D60322AC ON rbac_user_roles (role_id)');

        // wh_warehouses
        $this->addSql('CREATE TABLE wh_warehouses (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            name VARCHAR(80) NOT NULL,
            address VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        // wh_stock_items
        $this->addSql('CREATE TABLE wh_stock_items (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            sku_code VARCHAR(255) NOT NULL,
            sku_name VARCHAR(255) NOT NULL,
            quantity INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        // wh_stocks
        $this->addSql('CREATE TABLE wh_stocks (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            warehouse_id INT NOT NULL,
            stock_id INT NOT NULL,
            on_hands INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_436DA1445080ECDE ON wh_stocks (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_436DA144DCD6110 ON wh_stocks (stock_id)');

        // Constraints
        $this->addSql('ALTER TABLE catalog_product_attributes ADD CONSTRAINT FK_747A21D54584665A FOREIGN KEY (product_id) REFERENCES catalog_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE catalog_product_images ADD CONSTRAINT FK_1116EDC34584665A FOREIGN KEY (product_id) REFERENCES catalog_products (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rbac_user_roles ADD CONSTRAINT FK_C4230A76A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rbac_user_roles ADD CONSTRAINT FK_C4230A76D60322AC FOREIGN KEY (role_id) REFERENCES rbac_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wh_stocks ADD CONSTRAINT FK_436DA1445080ECDE FOREIGN KEY (warehouse_id) REFERENCES wh_warehouses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wh_stocks ADD CONSTRAINT FK_436DA144DCD6110 FOREIGN KEY (stock_id) REFERENCES wh_stock_items (id) ON DELETE CASCADE');
    }


    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE catalog_product_attributes DROP CONSTRAINT FK_747A21D54584665A');
        $this->addSql('ALTER TABLE catalog_product_images DROP CONSTRAINT FK_1116EDC34584665A');
        $this->addSql('ALTER TABLE rbac_user_roles DROP CONSTRAINT FK_C4230A76A76ED395');
        $this->addSql('ALTER TABLE rbac_user_roles DROP CONSTRAINT FK_C4230A76D60322AC');
        $this->addSql('ALTER TABLE wh_stocks DROP CONSTRAINT FK_436DA1445080ECDE');
        $this->addSql('ALTER TABLE wh_stocks DROP CONSTRAINT FK_436DA144DCD6110');
        $this->addSql('DROP TABLE catalog_product_attributes');
        $this->addSql('DROP TABLE catalog_product_images');
        $this->addSql('DROP TABLE catalog_products');
        $this->addSql('DROP TABLE rbac_roles');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE rbac_user_roles');
        $this->addSql('DROP TABLE wh_stock_items');
        $this->addSql('DROP TABLE wh_stocks');
        $this->addSql('DROP TABLE wh_warehouses');
    }
}
