<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315121239 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // wh_product
        $this->addSql('CREATE TABLE wh_product (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            sku_code VARCHAR(255) NOT NULL,
            sku_name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        // wh_stock
        $this->addSql('CREATE TABLE wh_stock (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            warehouse_id INT NOT NULL,
            product_id INT NOT NULL,
            on_hands INT NOT NULL,
            reserved INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE INDEX IDX_B225E3D5080ECDE ON wh_stock (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_B225E3D4584665A ON wh_stock (product_id)');

        // wh_warehouse
        $this->addSql('CREATE TABLE wh_warehouse (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        // FK
        $this->addSql('ALTER TABLE wh_stock ADD CONSTRAINT FK_B225E3D5080ECDE FOREIGN KEY (warehouse_id) REFERENCES wh_warehouse (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wh_stock ADD CONSTRAINT FK_B225E3D4584665A FOREIGN KEY (product_id) REFERENCES wh_product (id) ON DELETE CASCADE');

        // rbac_roles fix
        $this->addSql('ALTER TABLE rbac_roles ALTER permissions DROP DEFAULT');
    }


    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE wh_stock DROP CONSTRAINT FK_B225E3D5080ECDE');
        $this->addSql('ALTER TABLE wh_stock DROP CONSTRAINT FK_B225E3D4584665A');
        $this->addSql('DROP TABLE wh_product');
        $this->addSql('DROP TABLE wh_stock');
        $this->addSql('DROP TABLE wh_warehouse');
        $this->addSql('ALTER TABLE rbac_roles ALTER permissions SET DEFAULT \'[]\'');
    }
}
