<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311092717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rbac_roles (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, permissions JSON NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_487801545E237E06 ON rbac_roles (name)');
        $this->addSql('CREATE TABLE rbac_user_roles (user_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (user_id, role_id))');
        $this->addSql('CREATE INDEX IDX_C4230A76A76ED395 ON rbac_user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_C4230A76D60322AC ON rbac_user_roles (role_id)');
        $this->addSql('ALTER TABLE rbac_user_roles ADD CONSTRAINT FK_C4230A76A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rbac_user_roles ADD CONSTRAINT FK_C4230A76D60322AC FOREIGN KEY (role_id) REFERENCES rbac_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE users DROP roles');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rbac_user_roles DROP CONSTRAINT FK_C4230A76A76ED395');
        $this->addSql('ALTER TABLE rbac_user_roles DROP CONSTRAINT FK_C4230A76D60322AC');
        $this->addSql('DROP TABLE rbac_roles');
        $this->addSql('DROP TABLE rbac_user_roles');
        $this->addSql('ALTER TABLE users ADD roles JSON NOT NULL');
    }
}
