<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423112144 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, parent_id INT DEFAULT NULL, dtype VARCHAR(255) NOT NULL, warehouse_id INT DEFAULT NULL, stock_item_id INT DEFAULT NULL, quantity INT DEFAULT NULL, reason VARCHAR(255) DEFAULT NULL, correlation_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76727ACA70 ON document (parent_id)');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76727ACA70 FOREIGN KEY (parent_id) REFERENCES document (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76727ACA70');
        $this->addSql('DROP TABLE document');
    }
}
