<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260325160151 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial schema';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE rbac_roles (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(255) NOT NULL,
            permissions JSON NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_487801545E237E06 ON rbac_roles (name)');

        $this->addSql('CREATE TABLE users (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            email VARCHAR(180) NOT NULL,
            password VARCHAR(255) NOT NULL,
            type VARCHAR(50) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');

        $this->addSql('CREATE TABLE rbac_user_roles (
            user_id INT NOT NULL,
            role_id INT NOT NULL,
            PRIMARY KEY (user_id, role_id)
        )');
        $this->addSql('CREATE INDEX IDX_C4230A76A76ED395 ON rbac_user_roles (user_id)');
        $this->addSql('CREATE INDEX IDX_C4230A76D60322AC ON rbac_user_roles (role_id)');
        $this->addSql('ALTER TABLE rbac_user_roles ADD CONSTRAINT FK_C4230A76A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rbac_user_roles ADD CONSTRAINT FK_C4230A76D60322AC FOREIGN KEY (role_id) REFERENCES rbac_roles (id) ON DELETE CASCADE');

        $this->addSql('CREATE TABLE catalog_products (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            sku_code VARCHAR(255) NOT NULL,
            sku_name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE TABLE wh_warehouses (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(80) NOT NULL,
            address VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE TABLE wh_stock_items (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            sku_code VARCHAR(255) NOT NULL,
            sku_name VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE TABLE wh_stocks (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            warehouse_id INT NOT NULL,
            stock_id INT NOT NULL,
            on_hands INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY (id)
        )');
        $this->addSql('CREATE INDEX IDX_436DA1445080ECDE ON wh_stocks (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_436DA144DCD6110 ON wh_stocks (stock_id)');
        $this->addSql('ALTER TABLE wh_stocks ADD CONSTRAINT FK_436DA1445080ECDE FOREIGN KEY (warehouse_id) REFERENCES wh_warehouses (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE wh_stocks ADD CONSTRAINT FK_436DA144DCD6110 FOREIGN KEY (stock_id) REFERENCES wh_stock_items (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE wh_stocks DROP CONSTRAINT FK_436DA1445080ECDE');
        $this->addSql('ALTER TABLE wh_stocks DROP CONSTRAINT FK_436DA144DCD6110');
        $this->addSql('DROP TABLE wh_stocks');
        $this->addSql('DROP TABLE wh_stock_items');
        $this->addSql('DROP TABLE wh_warehouses');

        $this->addSql('DROP TABLE catalog_products');

        $this->addSql('ALTER TABLE rbac_user_roles DROP CONSTRAINT FK_C4230A76A76ED395');
        $this->addSql('ALTER TABLE rbac_user_roles DROP CONSTRAINT FK_C4230A76D60322AC');
        $this->addSql('DROP TABLE rbac_user_roles');
        $this->addSql('DROP TABLE users');
        $this->addSql('DROP TABLE rbac_roles');
    }
}
