<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312104451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rbac_permissions (name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F4AB496C5E237E06 ON rbac_permissions (name)');
        $this->addSql('CREATE TABLE rbac_role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX IDX_A670271BD60322AC ON rbac_role_permissions (role_id)');
        $this->addSql('CREATE INDEX IDX_A670271BFED90CCA ON rbac_role_permissions (permission_id)');
        $this->addSql('ALTER TABLE rbac_role_permissions ADD CONSTRAINT FK_A670271BD60322AC FOREIGN KEY (role_id) REFERENCES rbac_roles (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rbac_role_permissions ADD CONSTRAINT FK_A670271BFED90CCA FOREIGN KEY (permission_id) REFERENCES rbac_permissions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE rbac_roles DROP permissions');
        $this->addSql('ALTER TABLE rbac_roles DROP discr');
        $this->addSql('ALTER TABLE rbac_roles ALTER name TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER type TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE users ALTER type DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rbac_role_permissions DROP CONSTRAINT FK_A670271BD60322AC');
        $this->addSql('ALTER TABLE rbac_role_permissions DROP CONSTRAINT FK_A670271BFED90CCA');
        $this->addSql('DROP TABLE rbac_permissions');
        $this->addSql('DROP TABLE rbac_role_permissions');
        $this->addSql('ALTER TABLE rbac_roles ADD permissions JSON NOT NULL');
        $this->addSql('ALTER TABLE rbac_roles ADD discr VARCHAR(50) NOT NULL');
        $this->addSql('ALTER TABLE rbac_roles ALTER name TYPE VARCHAR(100)');
        $this->addSql('ALTER TABLE users ALTER type TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE users ALTER type SET DEFAULT \'member\'');
    }
}
