<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260312114627 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE rbac_role_permissions DROP CONSTRAINT fk_a670271bd60322ac');
        $this->addSql('ALTER TABLE rbac_role_permissions DROP CONSTRAINT fk_a670271bfed90cca');
        $this->addSql('DROP TABLE rbac_permissions');
        $this->addSql('DROP TABLE rbac_role_permissions');
        $this->addSql("ALTER TABLE rbac_roles ADD permissions JSON NOT NULL DEFAULT '[]'");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE rbac_permissions (name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_f4ab496c5e237e06 ON rbac_permissions (name)');
        $this->addSql('CREATE TABLE rbac_role_permissions (role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (role_id, permission_id))');
        $this->addSql('CREATE INDEX idx_a670271bfed90cca ON rbac_role_permissions (permission_id)');
        $this->addSql('CREATE INDEX idx_a670271bd60322ac ON rbac_role_permissions (role_id)');
        $this->addSql('ALTER TABLE rbac_role_permissions ADD CONSTRAINT fk_a670271bd60322ac FOREIGN KEY (role_id) REFERENCES rbac_roles (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rbac_role_permissions ADD CONSTRAINT fk_a670271bfed90cca FOREIGN KEY (permission_id) REFERENCES rbac_permissions (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE rbac_roles DROP permissions');
    }
}
